### ISSUE TITLE
ITI-105 und ITI-106 umsetzen

### ISSUE THREAD

**Issue by patrickwladowska** [gematik/spec-ISiK-Dokumentenaustausch#101]
Im Zuge der Kompatibilitätsbetrachtung vom Modul Dokumentenaustausch und der aktuellen Entwicklung von IHE-MHD werden folgende Änderungen vorgenommen:

AC:
1. Der IG verdeutlicht, dass nach einem POST einer DocumentMetadata die attachment.data extrahiert wird und separat gespeichert wird. Dies wird aus Performance-Gründen bei einer Suche festgelegt.
2. Es ist zu pürfen, ob sas Attachment beim POST einer DocumentReference MS und beim Abruf dieser unötig ist
3. Die URL der Metadata muss beim Einstellen des Documents leer bleiben und muss beim Abfragen im befüllt sein. Dieser passus muss sich im IG wiederfinden.
4. Über KDL-Codes sind XDS Type- und Class Codes erlaubt. Der Server hat diese nach dem Eingang zu befüllen. Dieser passus muss sich im IG wiederfinden.
5. Im IG wird der Passus POST-Interaktion den Submit-Document Teil substituieren. 
6. Im IG wird ein Beispiel für eine "gepostete" Dokumentenressource aufgenommen.
7. In der CapabilityStatement wird auf die Operationen SubmitDocument  verzichtet  und dafür die POST-Interaktion aufgenommen.
8. Die GenerateMetadata Operationen wird durch die der ITI-106 substituiert. (https://profiles.ihe.net/ITI/MHD/4.2.0-ballot/ITI-106.html)
9. In der CapabilityStatement wird auf die Operationen GenerateMetadata verzichtet dafür die POST-Interaktion wir aufgenommen.

**Comment by f-peverali** [comment]
@patrickwladowska , kann man schließen oder?
