### ISSUE TITLE
Änderungen an Anfragen in IG notwendig

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Dokumentenaustausch#102]
Änderungen an Anfragen (und ggf. auch Beispielen) in IG notwendig - siehe : https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BDOK.5D.20Suchparameter.20.20Beispiele

**Comment by f-peverali** [comment]
"Folgefehler" müssen ggf. noch behoben werden. @simoneOnFhir , kannst Du mir hier nochmal einen Hint geben?

**Comment by simoneOnFhir** [comment]
Istin 3.0.0-rc1 alles korrigiert.
