### ISSUE TITLE
rendering error in IG

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Dokumentenaustausch#109]
hier https://simplifier.net/guide/Implementierungsleitfaden%20ISiK-Modul%20Dokumentenaustausch/ImplementationGuide-markdown-Datenobjekte-DocumentReference?version=current : in der tabelle unter Anmerkungen zu Must-Support Feldern werden &quot; (gemeint ist "quot") nicht korrekt aufgelöst

GELÖST

**Comment by f-peverali** [comment]
@simoneOnFhir hättest Du dafür einen quickfix?

**Comment by f-peverali** [comment]
gemeint ist diese passage : 
 Update für Stufe 3:
  Die Ausnahme bildet die Interaktion &quot;Dokumentenbereitstellung&quot;, 
  bei der die Binärdaten des Dokumentes eingebettet in die DocumentReference an den Server übermittelt und dort dann in eine separate 
  Ressource ausgelagert und über Attachment.url referenziert werden.

**Comment by simoneOnFhir** [comment]
Ohje! Ich hatte das längst gefixed, aber offenbar vergessen einige lokale Änderungen zu commiten. (Nicht nur das sondern auch diverse andere Fixes) Ich habe jetzt mein lokales repo nochmal synchronisiert. Der PR hat dadurch jetzt deutlich mehr Änderungen. Auch diese Problem sollte damit behoben sein!

**Comment by f-peverali** [comment]
hier weiterhin rendering Problem (https://simplifier.net/guide/Implementierungsleitfaden%20ISiK-Modul%20Dokumentenaustausch/ImplementationGuide-markdown-AkteureUndInteraktionen?version=current) : [2:3.67.4.4 CapabilityStatement Resource](https://profiles.ihe.net/ITI/MHD/ITI-67.html#236744-capabilitystatement-resource)
Es gelten die Vereinbarungen gemäß

Command 'pagelink' could not render: Page not found.

**Comment by f-peverali** [comment]
Typische Szenarien mit Koexistenz beider Interaktionen:
Der Empfänger eines Subsystem-Berichtes gem. Modul "Basis" möchte vor der Verarbeitung des Dokumenteninhalts das Original zur Archivierung an einen Dokumentenserver gem. Modul "Dokumentenaustausch" übermitteln und die Herkunft der extrahierten Daten aus dem Dokument nachvollziehbar machen.

Empfohlenes Vorgehen:

Erzeugen einer DocumentReference-Ressource (siehe dazu $generate-metadata)
Übermittlung der DocumentReference sowie des Base64-codierten Bundles gemäß [Interaktion ISiK Modul Dokumentenaustausch Stufe 2](https://simplifier.net/guide/Implementierungsleitfaden%20ISiK-Modul%20Dokumentenaustausch/markdown-AkteureUndInteraktionen-Interaktion-Dokumentenbereitstellung?version=current)
Extraktion und [HIER FEHLT etwas -> @simoneOnFhir ggf. "Verarbeitung" oder "Persisitierung" ?] der verarbeitbaren Ressourcen aus dem Bundle

**Comment by simoneOnFhir** [comment]
da ist nur das "und" zuviel... 
Ich schau mal nach den Pagelinks...

**Comment by f-peverali** [comment]
alles klar, danke

**Comment by f-peverali** [comment]
fix with https://github.com/gematik/spec-ISiK-Dokumentenaustausch/pull/117/commits/ddce3156d711cda53191e9561f4464ab341f17b7
