### ISSUE TITLE
Versionierung von Dokumenten

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Dokumentenaustausch#124]
hier Input: https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BDOK.5D.20Versionierung.20von.20Dokumenten

Zu prüfen
Anforderungen bereits abgedeckt?
Wenn ja, klarer formulieren? -> ggf. Passus in IG zur Versionierung von Dokumenten hinzufügen?
Wenn nein, wie einbringnen?

FYI @jcaumann
```[tasklist]
### Tasks
- [ ] PTDATA-709
```

**Comment by f-peverali** [comment]
ggf. bei IHE und CDA schauen

**Comment by f-peverali** [comment]
Ggf. ist hier der IG noch nachzuschärfen, entsprechend den Feststellungen im Chat.

**Comment by simoneOnFhir** [comment]
...was Patrick sagt :)

Ist ein Stückweit auch schon hier im Unterkapitel "Dokumentenstatus" erklärt.
..und dadurch, dass es auf der DocumentReference Ressource nur die create-Interaktion gibt, siehe: https://simplifier.net/guide/Implementierungsleitfaden-ISiK-Modul-Dokumentenaustausch-Stufe-3/ImplementationGuide-markdown-Datenobjekte-DocumentReference?version=current#ImplementationGuide-markdown-DocumentReference-Interaktionen
Evtl. könnte man in letzterem Kapitel nochmal einen expliziten Satz sagen, dass die PUT-Interaktion NICHT Bestandteil dieser Spezifikation ist, da wir Kompatibilität mit IHE-XDS anstreben, wo das Änderung von Dokumenten nur über die Anlage und Verlinkung eines neuen Dokumentes möglich ist.

**Comment by simoneOnFhir** [comment]
...mit Link auf https://profiles.ihe.net/ITI/MHD/ITI-105.html#231054123-replace-transform-signs-and-append-associations

**Comment by f-peverali** [comment]
die Antwort sollte im .relatesto-Element im Comment-feld hinterlegt werden
