### ISSUE TITLE
[DOK] Kommentar inkonsistent mit dem Profil

### ISSUE THREAD

**Issue by mwedekind-dev** [gematik/spec-ISiK-Dokumentenaustausch#127]
Im ISiK Modul Dokumentenaustausch ist der Text in den Comments zum Element DocumentReference.type inkonsistent mit dem Profil. In Comments Text steht: 
> Im ISiK-Kontext ist die Typisierung eines Dokumentes mit Hilfe eines KDL-Codes **und** des IHE-XDS-Type-Codes erforderlich.

Allerdings ist die Kardinalität von DocumentReference.type.coding:KDL 1..1, also obligatorisch, und von DocumentReference.type.coding:XDS 0..1, also optional.

**Comment by f-peverali** [comment]
So wie ich es sehe beißen sich zwei Formulierungen:
zu DocumentReference.type.coding:XDS : "Die Übermittlung des XDS-Type-Codes ist im Rahmen der Dokumentenbereitstellung für Clients nicht verpflichtend, muss jedoch vom Server bei der Entgegennahme ggf. ergänzt und bei der Dokumentenabfrage zurückgegeben werden. Der XDS-Type-Code kann über die im Rahmen der [KDL-Spezifikation](https://simplifier.net/kdl) publizierten [ConceptMaps](https://simplifier.net/kdl/~resources?category=ConceptMap) aus dem KDL-Code ermittelt werden" -> erklärt warum XDS type im Profil die Kardinalität 0..1 .
und zu "DocumentReference.type" : "Im ISiK-Kontext ist die Typisierung eines Dokumentes mit Hilfe eines KDL-Codes und des IHE-XDS-Type-Codes erforderlich. Während ersterer eine feingranulare Dokumentenklassifikation für die gezielte Suche nach medizinischen udn Administrativen Dokumenten ermöglicht, ist letzterer für den einrichtungsübergreifenden Dokumentenautausch maßgeblich. Der XDS-Type-Code kann mit Hilfe der bereitgestellten [ConceptMaps](https://simplifier.net/kdl/~resources?category=ConceptMap) aus dem KDL-Code ermittelt werden. Weitere Typisierungen (z.B. nach SNOMED oder LOINC) sind uneingeschränkt erlaubt.
[Konsens der Arbeitgruppe vom 18.02.2022]"

-> Ich gehe davon aus, dass die Karindalität des Profils so intendiert gewesen ist. Ggf. lässt sich durch eine Anpassung der Formulierung unter "DocumentReference.type" der vermeintliche Widerspruch verhindern.

**Comment by f-peverali** [comment]
Mein Vorschlang zur Anpassung:

"Im ISiK-Kontext ist die Typisierung eines Dokumentes mit Hilfe eines KDL-Codes und des IHE-XDS-Type-Codes erforderlich [ergänzen mit:], jedoch ist der IHE-XDS-Type-Code bei Übermittlung nicht verpflichtend (s.u.)."

Ok @nextStep4me , oder habe ich etwas übersehen?

**Comment by nextStep4me** [comment]
Die Formulierung "erforderlich" klingt danach, dass der XDS-code immer gefüllt sein muss. Was ja durch die Kardinalität 0..* gar nicht verlangt wird. Also würde ich den Teil "... und des IHE-XDS-Type-Codes" weglassen.

Ein Dokumenten-Client kann also den XDS Code weglassen, ein Dokumenten-Server muss ihn bereitstellen? Wenn immer ein KDL Code eingetragen werden muss, wegen der Kardinalität 1..1, und es ConceptMaps gibt, die KDL auf das XDS ValueSet abbilden, ist der XDS Code ja eigentlich immer vorhanden. Dann wäre die Vorgabe des must-support Flags auch immer erfüllt, also sowohl Client als auch Server einer DocumentReference könnte immer KDL und XDS Codes einfüllen. Es müsste allerdings jeweils der Umgang mit ConceptMaps implementiert werden, was ggf. ein größerer Aufwand für Hersteller wäre.

@f-peverali Warum sollte also nur ein Client den XDS Code nicht mitsenden müssen und der Server muss es? Soll damit den Clients die Implementierung des Umgangs mit ConceptMaps erspart werden, weil dies ggf. für mobilen Anwendungen zu viel Aufwand bedeutet? Oder welcher Grund hat zu diesem Teil der Spec geführt?

**Comment by alexzautke** [comment]
Siehe https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BDOK.5D.20Inkonsistenter.20Kommentar/near/339799662
