### ISSUE TITLE
Deprecated operation name used in spec

### ISSUE THREAD

**Issue by mwedekind-dev** [gematik/spec-ISiK-Dokumentenaustausch#128]
Im Abschnitt "Typische Szenarien mit Koexistenz beider Interaktionen:" wird 2x die abgeschriebene Operation $generate-metadata verwendet. Vielleicht statt dessen auf den Abschnitt "Erzeugen von Metadaten (IHE MHD ITI-106 Generate Metadata)" verweisen?

**Comment by mwedekind-dev** [comment]
Ich habe gerade gelesen, dass $generate-metadata aus Stufe 2 durch eine Definition ersetzt wurde, die jetzt in einem IHE Profil definiert ist. Die ISiK Spec referenziert darauf und nach zwei Sprüngen ist man dann in der [neuen Definition von $generate-metadata](https://profiles.ihe.net/ITI/MHD/OperationDefinition-generate-metadata.html).

Ich finde das etwas unübersichtlich. $generate-metadata ist wenigstens auch im CapabilityStatement, aber von da gelangt man nicht zur IHE Definition.

Insofern ist $generate-metadata nicht deprecated und das Ticket kann geschlossen werden. Allerdings würde ich mir eine übersichtlichere Form wünschen, in der die ISiK Spec mit den FHIR und IHE Specs zusammen zu lesen ist.

**Comment by f-peverali** [comment]
Danke für den Input @mwedekind-dev , ich werde prüfen, wie wird die Spec lesbarer gestalten können.
