### ISSUE TITLE
Erläuterung von "Base64-codierten Bundles"

### ISSUE THREAD

**Issue by mwedekind-dev** [gematik/spec-ISiK-Dokumentenaustausch#129]
Die Spec erwähnt unter ["Typische Szenarien mit Koexistenz beider Interaktionen:"](https://simplifier.net/guide/Implementierungsleitfaden%20ISiK-Modul%20Dokumentenaustausch/ImplementationGuide-markdown-AkteureUndInteraktionen?version=current) 2x, das Base-64 kodierte Bundles mit den ISiKDokumentenMetadaten von einem Client versendet werden können. Im Abschnitt "Interaktion ISiK Modul Dokumentenaustausch Stufe 2: Dokumentenbereitstellung" steht dann noch:

> Content: DocumentReference mit Base64-codiertem Bundle vom Typ document eingebettet in DocumentReference.content.attachment.data)

Es wäre sehr hilfreich, dort, wo von Base64 kodierten Bundles geschrieben wird, genauer zu erläutern, dass es sich dabei bspw. um MIOs oder andere FHIR Documents handeln kann. Ich bin jedenfalls innerhalb eines Jahres bereits zweimal darüber gestolpert und konnte erst im [ISiK Chat dazu Hilfe bekommen](https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BDOK.5D.20Weiterverarbeitung.20von.20Ressourcen/near/340071887).

Außerdem: sollen so Base64 kodierte Document Bundles dann auch durch bspw. ein empfangendes FHIR Document Repository persistiert und bei Bedarf in Base64 kodierter Form wieder herausgegeben werden können? Das klingt für mich nicht sinnvoll. Allerdings wäre es auch inkonsistent zum sonstigen Umgang mit anderen Binärformaten, wie PDF. PDF wird ja auch direkt zurück gegeben. Entweder in einer abgefragten DocRef in attachment.url oder direkt als Binary FHIR Ressource. 
```[tasklist]
### Tasks
- [ ] PTDATA-706
```

**Comment by jcaumann** [comment]
In HL7v3 CDA gab es die Regel, dass im Body nur dann base64 kodierte Daten zulässig sind, wenn diese Daten nicht orginär strukturierte Daten sind. Sprich: In CDA wäre es nicht erlaubt, in einem strukturierten Container strukturierte Daten als base64 einzubetten. Eigentlich sinnvoll. Wir sollten daher zuerst einmal überlegen, wann sich überhaupt die Not ergeben kann, ein MIO als base64 in ein Bundle zu packen. Vielleicht ist das ja nur ein akademisches Szenario....

**Comment by mwedekind-dev** [comment]
In der Spec steht unter "Hinweise und Anmerkungen zur Implementierung von IHE MHD ITI-106 (Generate Metadata)" -> "[2:3.106.4.1.3 Expected Actions](https://profiles.ihe.net/ITI/MHD/ITI-106.html#23106413-expected-actions)":
> Die Unterstützung weiterer Input-Formate (z.B. CDA oder andere FHIR-Dokumente, wie MIOs, eRezept, eAU etc.) ist optional.

Es werden also potentielle Dokumentenformate aufgezählt, die dann, wie in der Spec beschrieben, base64 kodiert persistiert werden müssen. Wer mag, kann das machen, z.B. auch mit einem MIO. Der dabei bedachte Use Case ist wahrscheinlich, das Dokumente ISiK-konform an ein Archiv gesendet werden sollen, so dass man keine Archiv-spezifische API bedienen muss. Das ist aber nur eine Vermutung, es steht nirgends in der Spec. Das wäre aber sehr hilfreich, um z.B. zu verstehen, warum denn überhaupt angedacht ist, auch MIOs base64 kodiert irgendwohin zu senden. Es wäre darum aus meiner Sicht sehr überlegenswert, die Spec in dem Sinne zu erweitern und zuvor mit relevanten Interessengruppen zu prüfen, ob die überhaupt einen Bedarf daran haben, Archivsysteme mit einer einheitlichen ISiK-konformen API ansprechen zu können.

Sehr seltsam, aus meiner Sicht, wäre dann noch, wenn tatsächlich auch die ISiK-konforme Abfrage von base64 kodierten MIOs umgesetzt würde, die ja in der Spec so vorgesehen ist. Warum sollte das jemand tun wollen? Auch hier wäre eine Klärung in der Spec für mich hilfreich. Es könnte bspw. darauf verwiesen werden, dass es dafür keine bekannten Use Cases gibt und es darum nicht implementiert werden muss oder es könnten entsprechende Use Cases erläutert werden.

**Comment by f-peverali** [comment]
https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BDOK.5D.20Base64.20kodierte.20FHIR.20Documents.20herausgeben.3F
