### ISSUE TITLE
Toter link zur Liste der bestätigungsrelevanten Systeme

### ISSUE THREAD

**Issue by mwedekind-dev** [gematik/spec-ISiK-Dokumentenaustausch#130]
Der Link "Überblick bestätigungsrelevante Systeme" auf https://www.ina.gematik.de/themenbereiche/informationssysteme-im-krankenhaus führt auf eine nicht mehr existente Seite in Simplifier. Inzwischen existiert ja diese Liste von bestätigungsrelevanten Systemen von der DKG: https://www.dkgev.de/themen/digitalisierung-daten/elektronische-datenuebermittlung/datenuebermittlung-nach-373-sgb-v-informationssysteme-im-krankenhaus/ 
Sollte vielleicht lieber dorthin verlinkt werden?

**Comment by f-peverali** [comment]
@steffenhennecke könntest Du dir das anschauen?

**Comment by f-peverali** [comment]
gelöst
