### ISSUE TITLE
[DOK] Datenqualität für von Patienten bereitgestellte Dokumente (Stufe 3) 

### ISSUE THREAD

**Issue by mwedekind-dev** [gematik/spec-ISiK-Dokumentenaustausch#133]
ISiKDokumentenMetadaten verlangt, dass diverse Codes zur Klassifikation des Dokumentes mitgegeben werden, bspw. der KDL Code im type Element oder andere Codes in context.facilityType oder context.practiceSetting. Ich glaube, dass viele Dokumente von Patienten in bpsw. ein Patientenportal oder eine Gesundheitsakte eingestellt werden, um sie von dort mit dem Krankenhaus zu teilen. Aus der Vielzahl an möglichen Kodierungen werden die wenigsten Patienten richtig auswählen. Abgesehen davon ist es ein ziemlicher Aufwand, sich für jedes Dokument durch diese Menge an Kodierungen zu lesen. Auch das Patientenportal oder die Gesundheitsakte können Patienten da nur wenig unterstützen, weil sie die nötigen Informationen nicht haben.
Ich befürchte, dass dann einfach irgendetwas in die ISiKDokumentenMetadaten eingetragen wird, was im schlimmsten Fall zu Fehlentscheidungen führen kann. Im besten Fall erzeugt es unnötigen Aufwand, wenn es Dokumente von Patienten gibt, deren Kodierung das Krankenhaus nicht vertrauen kann und Dokumente, die über Patienten von med. Fachkollegen kommen, deren Kodierung man vertrauen kann.

Für diese Problemlage wünsche ich mir eine Klarstellung in der Spec.
```[tasklist]
### Tasks
- [ ] PTDATA-682
```

**Comment by andreasghenkel** [comment]
ch stimme dem Hinweis voll und ganz zu. Meiner Meinung nach sollten selbst erstellte Unterlagen des Patienten genauso bewertet werden wie Unterlagen, die von einem Patienten mitgebracht werden und erst dann Teil der medizinischen Dokumentation werden, wenn ein Arzt sie aktiv in einen Befund oder Brief einbezieht.

Allerdings sollten selbst erstellte Unterlagen klar als solche gekennzeichnet werden, um zu signalisieren, dass sie möglicherweise nicht zuverlässig sind, weder inhaltlich noch in Bezug auf ihre Klassifizierung. Eine solche Kennzeichnung sollte Teil der Spezifikation sein.

Es wäre jedoch problematisch, wenn es keine Klassifizierungsvorschriften für selbst erstellte Unterlagen gäbe. Im Allgemeinen sollte man davon ausgehen, dass der Patient die richtige Klassifizierung vornimmt. Es ist jedoch wichtig, dass die Hersteller dafür sorgen, dass die Auswahl für den Patienten gut verständlich ist. Dies ist meiner Meinung nach jedoch nicht Teil der Spezifikation.

**Comment by mwedekind-dev** [comment]
Ich finde den Ansatz gut, zu kennzeichnen, dass eine DocumentReference vom Patienten übermittelt wird und unklar ist, ob das Dokument korrekt klassifiziert wurde. Ich sehe allerdings direkt in DocumentReference kein Element, mit dem das realisiert werden kann. Dafür braucht es, denke ich, eine Extension. Vielleicht sowas wie "documentSource", die eine Reference auf Patient oder Practitioner sein kann? Für den Practitioner kann ja, analog zum author Element, erst einmal ein display-String ausreichend sein.
Was meint ihr?

**Comment by mwedekind-dev** [comment]
Darüber hinaus muss halt in realen Implementierungen getestet werden, inwieweit Hersteller mit ihren Lösungen Patienten dabei unterstützen können, die richtigen Kodierungen auszuwählen. Da bin ich immer noch skeptisch, ob das immer gut funktioniert... Dazu bräuchte die Softwarelösung neben den Eingaben des Patienten i.d.R. mehr Informationen. Idealerweise werden die Dokumente eben direkt von einer med. Fachkraft richtig kodiert ins Patientenportal oder eine App geladen. Ist aber aktuell auch nicht sehr verbreitet.

**Comment by f-peverali** [comment]
Vielen Dank für die Hinweise, @mwedekind-dev , @andreasghenkel . Ich werde mich um einen baldigen Lösungsvorschlag bemühen und das Thema auch für das Community Meeting am 17.3. auf die Agenda setzen.

**Comment by f-peverali** [comment]
Womöglich zu lösen über Patient als DocumentReference.author (zu klären ob konsistent mit Operations)

**Comment by f-peverali** [comment]
Bessere Lösung erscheint Anpassung des VS für .type z.B. mit KDL-Liste als Include + eigenem Code für Dokumente direkt vom Patienten oder anderweitig ungesicherte Dokumentation

**Comment by alexzautke** [comment]
Dokumente die von einem Patientenportal aus übermittelt werden können zunächst mit AM160199 | http://dvmd.de/fhir/CodeSystem/kdl | Sonstiges patienteneigenes Dokument kodiert werden. Der facilityTypeCode kann in den meisten Fällen harnkodiert werden.
