### ISSUE TITLE
Hinweis UUID - OID hinzufügen (Stufe 3 / Stufe 2 + 1)

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Dokumentenaustausch#137]
siehe https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BDOK.5D.20OID.20im.20DocumentReference.20Beispiel.20verstehen/near/344796428

```[tasklist]
### Tasks
- [ ] PTDATA-710
```

**Comment by alexzautke** [comment]
+1 für den Hinweis, dass eine OID auf Basis einer UUID erzeugt werden kann

**Comment by jcaumann** [comment]
Die Wurzel 2.25 scheint ja von ihrer Beschreibung her genau für so einen Zweck da zu sein (UUID im OID-Format ohne Verpflichtung zur Registrierung an einem OID-Repository). Nach meinem Dafürhalten ist das dann nichts anderes, als wenn man mit dem Prefic "urn:oid:" eine OID zu einer URN macht. Der große Vorteil ist, dass eine UUID fix generiert ist, während ein OID-Management ein Albtraum ist. 
Vielleicht sollten wir das aber garnicht in die ISiK Spezifikation selbst aufnehmen, sondern mal anfangen, einen "ISiK Leitfaden" oder "ISiK Good Practice Guide" zu schreiben, wo dann alle guten Tipps und Ideen aus den verschiedenen Diskussionen reinkommen. Dann kann der normative Teil kompakt bleiben und in den Leitfaden kommen dann handlungsorientierte Darstellungen auf Basis von Szenarien. Nachteil ist, dass man dann bei Spec-Änderungen potenziell 2 Dokumente anfassen muss.

**Comment by f-peverali** [comment]
Formulierung ggf. analog zu Abschnitt (Composition.identifier) hier https://simplifier.net/guide/implementierungsleitfadenisik-basismodul/ImplementationGuide-markdown-Datenobjekte-Datenobjekte-BerichtSubsystem?version=current

**Comment by f-peverali** [comment]
@jcaumann das ist eine nicht-normative Änderung, richtig?
würde ich ggf. depriorisieren und dafür auch in die Stufe 1 und 2 einarbeiten als TC,

**Comment by jcaumann** [comment]
> @jcaumann das ist eine nicht-normative Änderung, richtig? würde ich ggf. depriorisieren und dafür auch in die Stufe 1 und 2 einarbeiten als TC,

genau. Das ist nur eine Information zu einer zulässigen Befüllung des Identifiers.
