### ISSUE TITLE
IHE-Terminologie unvollständig und validiert nicht

### ISSUE THREAD

**Issue by simoneOnFhir** [gematik/spec-ISiK-Dokumentenaustausch#57]
Die aktuell referenzierten Versionen der IHE-XDS-ValueSets sind
* nicht aktuell
* enthalten teilweise defekte Links
* enthalten keine Expansions
* erzeugen Fehler bei der Validierung

Kann erst korrigiert werden, wenn IHE Deutschland ein korrigiertes Package der XDS-ValueSets und-CodeSysteme bereitstellt.
```[tasklist]
### Tasks
- [ ] PTDATA-679
```

**Comment by simoneOnFhir** [comment]
IHE macht da leider gar nichts. Alex Zautke ist gemeinsam mit Kai Heitmann dabei, sich um ein korrektes Release der Terminologie zu kümmern.

**Comment by f-peverali** [comment]
Siehe dazu auch ANFISK 135

**Comment by amerzwe** [comment]
Neben der oben genannten Thematik besteht das Problem, dass es kein eindeutiges Mapping zwischen KDL und XDS Class / Type Codes gibt. :
KDL Codes mit "sonstige *",
Mapping entält Code UNK, der bei IHE -Deutschland nicht existiert.
Beispiele:  SD130199, UB999997
Vorschlag: Bereitstellung eines XDS typeCodes  auf Basis eines KDL Codes durch den Server sollte nicht verpflichtend sein.

**Comment by alexzautke** [comment]
Wir fügen einen Hinweis hinzu, dass es sich bei dem UNK-Code um keinen IHE-Code handelt sondern um einen Code aus https://terminology.hl7.org/1.0.0/CodeSystem-v3-NullFlavor.html

**Comment by alexzautke** [comment]
Die vollständig validierbaren ValueSets sind nun in diesem Package vorhanden: https://simplifier.net/packages/de.ihe-d.terminology
