### ISSUE TITLE
Dependency auf KDL 2022 aktualisieren

### ISSUE THREAD

**Issue by simoneOnFhir** [gematik/spec-ISiK-Dokumentenaustausch#69]

**Comment by simoneOnFhir** [comment]
Zum Zeitpunkt der Publikation von ISiK war KDL 2022 noch nicht released

**Comment by simoneOnFhir** [comment]
Package ist jetzt draußen.

**Comment by f-peverali** [comment]
gelöst mit https://github.com/gematik/spec-ISiK-Dokumentenaustausch/pull/91/commits/1168c29b3a3412b8add83236b3fd8cc978bf0cd6 FYI @patrickwladowska
