### ISSUE TITLE
Abgleich mit neuer IHE-Transaction ITI-105 "Simplified Publish" prüfen

### ISSUE THREAD

**Issue by simoneOnFhir** [gematik/spec-ISiK-Dokumentenaustausch#79]
http://build.fhir.org/ig/IHE/ITI.MHD/branches/simplifed-publish/ITI-105.html
Eventuell unsere Transaction zurückziehen und auf ITI-105 umschwenken?
Könnte mand as in einer Technical Correction machen oder erst in Stufe 3?
Welche Konsequenzen hätte das insbesondere in Bezug auf Updates?

Ich sehe auf den ersten Blick nur den Unterschied, dass das Binary in das Dokument eingebettet werden muss. (Und dass das POST ggf. nicht als POST sondern als POST+PUT verarbeitet wird).

**Comment by simoneOnFhir** [comment]
Rücksprache mit bvitg AG Interop...

**Comment by simoneOnFhir** [comment]
Warum Binary aus Basis entfernen?! Das brauchen wir noch für den Dokumentenabruf und die Terminplanung!

**Comment by mrwhitening-max** [comment]
Absolut richtig. Danke für den Hinweis. @simoneOnFhir

**Comment by patrickwladowska** [comment]
Absolut richtig, danke für den Hinweis. @simoneOnFhir

**Comment by f-peverali** [comment]
siehe auch : https://chat.fhir.org/#narrow/stream/179223-ihe/topic/ITI.20public-comment

**Comment by tobiasgirardet** [comment]
#100

**Comment by simoneOnFhir** [comment]
in 3.0.0-rc1 erledigt
