### ISSUE TITLE
Fix DocumentReference Beispiel `dok-beispiel-server`

### ISSUE THREAD

**Issue by ylboerner** [gematik/spec-ISiK-Dokumentenaustausch#80]
Das`DocumentReference` Beispiel `dok-beispiel-server` missachtet das Binding des Feldes `context.practiceSetting`. Dies sollte gefixt werden.

**Comment by patrickwladowska** [comment]
@ylboerner wo würdest Du eine Missachtung im Beispiel "dok-beispiel-client" erkennnen ?

**Comment by ylboerner** [comment]
@patrickwladowska Du hast vollkommen recht, dort ist es richtig. Nur `dok-beispiel-server` ist falsche. Ich habe die Beschreibung und den Titel angepasst. Danke!

**Comment by f-peverali** [comment]
gelöst mit https://github.com/gematik/spec-ISiK-Dokumentenaustausch/pull/89
