### ISSUE TITLE
Copy&Paste error in ISiKNachricht spec

### ISSUE THREAD

**Issue by nextStep4me** [gematik/spec-ISiK-Dokumentenaustausch#85]
In the chapter "Interaktionen" of https://simplifier.net/guide/isik-terminplanung/ImplementationGuide-markdown-Datenobjekte-ISiKNachrichtCommunication?version=current, a copy&paste error seems to have slipped through:

> GET [base]/Slot?subject=Patient/ISiKPatientExample
> GET [base]/Slot?recipient=Practitioner/ISiKPractitionerExample
> GET [base]/Slot?sender=Practitioner/ISiKPractitionerExample

I guess, Slot should be replaced with Communication.

**Comment by alexzautke** [comment]
Thanks for noticing. Will be fixed in https://github.com/gematik/spec-ISiK-Terminplanung/pull/51
