### ISSUE TITLE
Packages auf fhir.registry publiziert?

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Dokumentenaustausch#90]
Zu prüfen, ob alle ISIK/ISIP packages in simplifier auf die fhir.registry publiziert wurden.
Background: in simplifier war ein admin flag zu "publish on fhir.registry" auf false gesetzt
FYI @patrickwladowska

**Comment by f-peverali** [comment]
zu prüfen für alle packages, vor allem Basis

**Comment by f-peverali** [comment]
sollen wir das priorisieren @patrickwladowska ?

**Comment by alexzautke** [comment]
Packages sind nun alle unter registry.fhir.org zu finden.
