### ISSUE TITLE
Falscher Link auf IG

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiK-Dokumentenaustausch#99]
der Link von Simplifier zum Implementierungsleitfaden beim Modul Dokumententenaustausch ist falsch (https://simplifier.net/guide/isik-sicherheit/ImplementationGuide-markdown-ScopesAndLaunchContext?version=current -> der verweist aktuell auf das Modul sicherheit)

siehe hinweis aus zulip: https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BDOK.5D.20falscher.20Link.20auf.20Simplifier

**Comment by patrickwladowska** [comment]
Leider nicht. Diese ist n.m.a.E. Bestandteil von Simplifier.

**Comment by alexzautke** [comment]
Nein, die kann man nur in Simplifier direkt editieren.
